### ISSUE TITLE
PHP warning if $TIME_ZONE doesn't exist

### ISSUE THREAD

**Issue by bparks** [bparks/pails#17]
[Sat Jul 25 16:23:56 2015] PHP Notice:  Undefined variable: TIME_ZONE in /Users/bparks/working/social_wall/vendor/pails/pails/index.php on line 22

**Comment by dstockto** [comment]
I think this is fixed.

```
if (!isset($TIME_ZONE) || trim($TIME_ZONE) == '')
```

**Comment by bparks** [comment]
There is one spot in the tools where it is not fixed, but they have since been moved to their own repo, so this can be closed.
